### ISSUE TITLE
admin web: start working on status/output web UI

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky-aws#20]
## Done
 - [x] decide on framework (reactjs vs. vue vs. something else?) ***<-- nextjs + reactjs***
 - [x] page that displays requests <-- built on web service that lists contents of bucket/requests
 - [x] page that displays request status <-- built on web service that parses and displays the status file data
 - [x] page that displays run log file
 - [x] pagination for requests page
 - [x] get build working
 - [x] don't hardcode http://localhost:3000/ for API requests
 - [x] Add spinner gif placeholders until data area loaded in various info blocks (run input, run log, request status, etc.)
 - [x] page that displays fire-specific information - would load input data from s3, parse, and load specific fire info
 - [x] add caching on all GETs of s3 data <-- all but listing requests and getting status json
 - [x] url encode all id's (request, run) in url paths (pages and apis), and anything in queries
 - [x] add output page(s) 
   - [x] view output json
   - [x] list other files, with links to download
   - [ ] link to fetch tar.gz from s3

## TODO
 - [ ] button in header to clear cache (and reload page, if not on requests page or request page)
 - [ ] get basePath+accessPath working so that we can proxy non-root path when deployed (see https://levelup.gitconnected.com/deploy-your-nextjs-application-on-a-different-base-path-i-e-not-root-1c4d210cce8a)
 - [ ] run demo somewhere behing .htaccess
 - [ ] sort requests by time, decreasing ***<--AWS doesn't seem to support this.  Alternatively, paginate by month, with current month shown on page load, and keep current pagination in case any month has more requests than per-page limit***
 - [ ] add instructions for creating new credentials, with only s3 read privileges <-- in dev, can just use same credentials as are used for by run-bluesky
 - [ ] regression tests for admin APIs
 - [ ] Update APIs to return appropriate HTTP statuses (e.g. 404 when output doesn't exist, 500 for other fialures, etc.)

## Lower Priority TODOs
 - [ ] when using json viewer, there is time between when data is loaded and viewer is rendered; the loading spinner goes away after data load; ideally it will show until json viewer is rendered

## Maybe
 - [ ] create docker-compose.yml and reboot script
 - [ ] eventually protect by auth (maybe not necessary)
