### ISSUE TITLE
More detailed run status tracking

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky-aws#29]
Follow up to #21

 - [ ] for runs that depend on met data:  after installing bluesky, and just before running it, check for met; if not available, wait until it arrives, setting run status to WAITING until is available
 - [ ] after run completes, check output for 'error' and set run status to 'failure' if necessary
 - [ ] once we support running multiple fires sequentially on a single instance, set run status to waiting for each run/fire while it waits for other(s) to finish
